import Head from "next/head";
import Banner from "./components/Banner";
import About from "./components/About";
import styles from "./page.module.css";
import BodyOfWork from "./components/bodyofwork";
import ContactSection from "./components/contact";

import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

export default function Home() {
  return (
    <div className={styles.back}>
      <Head>
        <title>MLG</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section>
          <div className={styles.back}></div>
          <Banner />
        </section>
        <section>
          <About></About>
        </section>
        <section>
          <BodyOfWork></BodyOfWork>
        </section>
        <section>
          <ContactSection></ContactSection>
        </section>
      </main>
    </div>
  );
}
